# load General Purpose Memory Mapped driver 

epicsEnvSet "EPICS_CA_MAX_ARRAY_BYTES", "131072"

require "SynApps"
require "s7gpac", "koprek_w"
 
# epicsEnvSet s7gpacDebug 6

#  s7plcConfigure   ( PLCname,       IPaddr,     port, inSize,  outSize, bigEndian, recvTimeout, sendIntervall) 
#___________________________________________________________________________________________                     
# Button BPM Server                                                                                                  
#___________________________________________________________________________________________                     
#  __                                              
   s7gpacConfigure  ("IPC1587",      "ipc1587",    51234,    628,       72,         1,       10000,           200)    
   s7gpacConfigure  ("IPC1587-BUT1", "ipc1587",    51235,  45884,      308,         1,       10000,           200)    
   s7gpacConfigure  ("IPC1587-BUT2", "ipc1587",    51236,  45884,      308,         1,       10000,           200)
   s7gpacConfigure  ("IPC1587-BUT3", "ipc1587",    51237,  45884,      308,         1,       10000,           200)    
   s7gpacConfigure  ("IPC1587-BUT4", "ipc1587",    51238,  45884,      308,         1,       10000,           200)    
                         
#___________________________________________________________________________________________                     
# Button BPM Service Server                                                                                                  
#___________________________________________________________________________________________                     
#   s7gpacConfigure  ("EXFEL-BUTCFG",   "ipc1520",   51245,   6884,      132,         1,        10000,  				 200)    
